games_played <- tribble(
  ~won, ~def, ~day,
  "Sujoy", "Darren", NA_integer_,
  "Brian", "Gabe", NA_integer_,
  "Shibo", "Sandy", NA_integer_,
  "Darren", "Adam", NA_integer_,
  "Shibo", "Gabe", NA_integer_,
  "Brian", "Adam", NA_integer_,
  "Darren", "Sandy", NA_integer_,
  "Gabe", "Darren", NA_integer_,
  "Sujoy", "Justin", NA_integer_,
  "Sujoy", "Gabe", NA_integer_,
  "Adam", "Justin", NA_integer_,
  "Sujoy", "Adam", NA_integer_,
  "Sujoy", "Justin", NA_integer_,
  "Sujoy", "Adam", NA_integer_,
  "Darren", "Sujoy", NA_integer_,
  "Darren", "Justin", NA_integer_,
  "Sujoy", "Gabe", NA_integer_,
  "Gabe", "Adam", NA_integer_,
  "Gabe", "Adam", NA_integer_,
  "Gabe", "Adam", NA_integer_,
  "Adam", "Steve", NA_integer_,
  "Sujoy", "Adam", NA_integer_,
  "Sujoy", "Steve", NA_integer_,
  "Adam", "Steve", NA_integer_,
  "Darren", "Shibo", NA_integer_,
  "Steve", "Justin", NA_integer_,
  "Sujoy", "Adam", NA_integer_,
  "Sujoy", "Shibo", NA_integer_,
  "Darren", "Steve", NA_integer_,
  "Shibo", "Justin", NA_integer_,
  "Darren", "Adam", NA_integer_,
  "Sujoy", "Steve", NA_integer_,
  "Darren", "Sujoy", NA_integer_,
  "Shibo", "Adam", NA_integer_,
  "Steve", "Shibo", NA_integer_,
  "Darren", "Adam", NA_integer_,
  "Sujoy", "Darren", NA_integer_,
  "Brian", "Steve", 20191114,
  "Shibo", "Steve", 20191114,
  "Sujoy", "Shibo", 20191114,
  "Sujoy", "Steve", 20191114,
  "Sujoy", "Brian", 20191114,
  "Shibo", "Sandy", 20191114,
  "Brian", "Shibo", 20191114,
  "Sandy", "Steve", 20191114,
  "Sujoy", "Sandy", 20191114,
  "Brian", "Sandy", 20191114
  "Darren", "Gabe",
  "Sujoy", "Justin",
  "Gabe", "Steve",
  "Sujoy", "Gabe",
  "Darren", "Sujoy",
  "Darren", "Steve",
  "Steve", "Justin",
  "Gabe", "Sujoy",
  "Gabe", "Steve",
  "Darren", "Gabe"
)